modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/Champions/issues"
logoFile="champions_icon.png"
logoBlur=false
[[mods]]
modId="champions"
version="${version}"
displayName="Champions"
displayURL="https://github.com/TheIllusiveC4/Champions/"
authors="C4"
description='''
Creates elite mobs of different rarities, with enhanced stats and extra abilities.
'''
[[dependencies.champions]]
  modId="forge"
  mandatory=true
  versionRange="${forge_version_range}"
  ordering="NONE"
  side="BOTH"
[[dependencies.champions]]
  modId="minecraft"
  mandatory=true
  versionRange="${mc_version_range}"
  ordering="NONE"
  side="BOTH"
[[dependencies.champions]]
  modId="scalinghealth"
  mandatory=false
  versionRange="[6.3.0,)"
